version: "2"
services:
  mail:
    image: tvial/docker-mailserver
    restart: unless-stopped
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    environment:
      SSL_TYPE: ${SSL_TYPE}
      SASL_PASSWD: ${SASL_PASSWD}
    volumes:
      - ./var/maildata:/var/mail
      - ./config:/tmp/docker-mailserver:ro
